### PR TITLE
Declutter Codebase

### PR DESCRIPTION
**Pull request by kimbochen**
- Replaced data preprocessing with a simulated dataset
- Added config for LLaMA 3.1 models
- Replaced configurator with the Python Fire library
- Reimplemented GPT and LLaMA. Verified with unit tests
- Refactored `train.py` to have only single-node training
- Added more accurate FLOP counting of GPT and LLaMA models

### CODE REVIEW

**Comment by OrenLeung** [comment]
@kimbochen LGTM, but can you add back DDP in this PR or a followup?

**Comment by kimbochen** [comment]
Added DDP training in `train_ddp.py` with profiling.

**Comment by OrenLeung** [comment]
@kimbochen can you add some MFUs numbers to this PR so we know that we are in the correct OOM

**Comment by kimbochen** [comment]
I replaced TensorBoard trace with Chrome trace.

Here are the rough MFU numbers:

| Model | GPU Setup | Configs | MFU (%) |
| :- | :- | :- | :-: |
| `gpt2-125m` | Single GPU | `bsz=64` | ~35 |
| `gpt2-125m` | Single GPU | `bsz=64 pt-compile` | ~40 |
| `gpt2-125m` | Multi-GPU DDP | `bsz=64` | ~35 |
| `gpt2-125m` | Multi-GPU DDP | `bsz=64 `pt-compile` | ~40 |

**Comment by OrenLeung** [comment]
thanks LGTM!!

**Pull request merged**
